"""Pure PDF analysis — inspect PDF bytes for text layers, page counts, OCR stamps.

No filesystem access. All inputs are ``bytes``, all outputs are ints/bools/strs.

This is the single decision point for the vision-attach policy:
when to render PDF pages as images for the LLM instead of trusting
the embedded text layer.

Extracted from archivist.py so each function can be unit-tested
in isolation with synthetic PDF bytes (Pillow can produce minimal
valid PDFs for test fixtures)."""

from __future__ import annotations

import io
from pypdf import PdfReader

# Producer / Creator strings written by tools that build a text layer
# by running OCR over rendered page images. Their text is searchable
# but routinely garbled (jumbled reading order, dropped characters) —
# we can't trust it the way we trust a native-text PDF authored in
# Word, LaTeX, or a CMS-generated invoice.
_OCR_LAYER_TOOLS = ("ocrmypdf", "tesseract")

# Default cap on how many PDF pages we'll attach to a vision call.
# A typical render at low res costs 1-3K tokens per page, so 5 pages
# is comfortable on a 32K-context model; households running a larger
# context can raise this via the archivist bot's `vision_max_pdf_pages`
# setting. Past the cap we skip vision and trust the (possibly
# imperfect) text layer. Short docs (booking confirmations, receipts,
# single-page letters) stay under this and get vision.
DEFAULT_VISION_MAX_PDF_PAGES = 5

# Default cap on the LLM reformat pass for PDFs. Reformat recovers
# layout from column-flattened or OCR-jumbled text -- high value on a
# 1-page invoice (a wall of text becomes a readable markdown block),
# low value on a 30-page contract where one LLM call can't fit the
# content. The reformat cap shares the same "short doc, full
# attention" reasoning as the vision cap; both come from bot config so
# households tune them together for their model's context.
DEFAULT_REFORMAT_MAX_PDF_PAGES = 5


def has_text_layer(pdf_bytes: bytes) -> bool:
    """Best-effort check: does this PDF carry an embedded text layer?

    Native-text PDFs (contracts, invoices generated by software, research
    papers) return True. Scanned PDFs built from photographed pages, and
    the archivist's own scan-mode-generated PDFs, return False. Any
    parsing error is logged at debug level and treated as 'no text
    layer' so the caller still proceeds — this is best-effort assistance,
    not a gate on correctness.

    Only the first three pages are inspected. Text layers are either
    present throughout or absent throughout in practice, and sampling
    keeps the check cheap on a 70-page paper.

    Args:
        pdf_bytes: Raw PDF file bytes.

    Returns:
        True if at least one of the first three pages has extractable text.
    """
    try:
        reader = PdfReader(io.BytesIO(pdf_bytes))
    except Exception:
        return False
    for page in reader.pages[:3]:
        try:
            if page.extract_text().strip():
                return True
        except Exception:
            continue
    return False


def has_ocr_text_layer(pdf_bytes: bytes) -> bool:
    """Best-effort: does the text layer look machine-OCR'd, not authored?

    Checks the PDF's ``/Producer`` and ``/Creator`` metadata for known OCR
    tools (OCRmyPDF, Tesseract). Both ride in the file's ``DocumentInfo``
    dictionary and survive Paperless's own ingestion — OCRmyPDF stamps
    itself when it inserts the searchable text layer.

    Any parsing error returns False so we fall through to trusting the
    text layer (the conservative choice — better an occasional bad
    classification than re-rendering every research-paper PDF).

    Args:
        pdf_bytes: Raw PDF file bytes.

    Returns:
        True if the producer/creator metadata mentions a known OCR tool.
    """
    try:
        reader = PdfReader(io.BytesIO(pdf_bytes))
        info = reader.metadata or {}
    except Exception:
        return False
    blob = " ".join(str(v or "") for v in (info.get("/Producer"), info.get("/Creator"))).lower()
    return any(tool in blob for tool in _OCR_LAYER_TOOLS)


def pdf_page_count(pdf_bytes: bytes) -> int:
    """Number of pages in the PDF, or 0 on parse failure.

    Used to gate the vision-attach decision: a long OCR'd PDF would
    otherwise burn one image token per page. Returns 0 for unreadable
    files so the caller's ``<= vision_max_pages`` comparison treats
    them as "short enough" — vision still attaches and the renderer
    handles its own failures gracefully.

    Args:
        pdf_bytes: Raw PDF file bytes.

    Returns:
        Page count, or 0 if the file can't be parsed.
    """
    try:
        return len(PdfReader(io.BytesIO(pdf_bytes)).pages)
    except Exception:
        return 0


def should_attach_vision(
    has_text_layer: bool,
    has_ocr_text_layer: bool,
    page_count: int,
    vision_max_pages: int = DEFAULT_VISION_MAX_PDF_PAGES,
) -> bool:
    """Single decision point for PDF vision-attach policy.

    Three cases:
      - No text layer (true scan) → attach vision; it's the only signal.
      - Text layer present AND machine-OCR'd AND short enough
        to be worth the tokens → attach vision so the model can
        override the garbled OCR via the ``VISION VS OCR`` prompt rule.
      - Otherwise (native-text PDF, or long OCR'd PDF) → no vision.
        Native text layers are trustworthy; long OCR'd PDFs cost too
        many image tokens to be worth the override on each page.

    ``page_count`` is only consulted when there IS a text layer — for
    scans we render whatever's there (partial classification on a long
    scan beats none). ``vision_max_pages`` is the per-household cap
    from `archivist-bot.toml`; the default is a safe lower bound for
    small-context models.

    Args:
        has_text_layer: Whether the PDF has an embedded text layer.
        has_ocr_text_layer: Whether the text layer looks machine-OCR'd.
        page_count: Number of pages in the PDF.
        vision_max_pages: Per-household cap on attached pages.

    Returns:
        True when the classifier should receive image attachments.

    Examples:
        >>> should_attach_vision(False, False, 0)   # true scan
        True
        >>> should_attach_vision(True, True, 3)     # short OCR'd PDF
        True
        >>> should_attach_vision(True, True, 30)    # long OCR'd PDF
        False
        >>> should_attach_vision(True, False, 5)    # native-text PDF
        False
        >>> should_attach_vision(True, False, 30)   # long native-text
        False
        >>> should_attach_vision(True, True, 15, vision_max_pages=20)
        True
    """
    if not has_text_layer:
        return True
    if has_ocr_text_layer and page_count <= vision_max_pages:
        return True
    return False


def should_reformat_pdf(
    page_count: int,
    reformat_max_pages: int = DEFAULT_REFORMAT_MAX_PDF_PAGES,
) -> bool:
    """Should we run the LLM reformat pass on this PDF?

    Short PDFs (≤5 pages) benefit from layout recovery — a two-column
    invoice extracts as a wall of run-on lines, and reformat cleans
    it up. Long PDFs would blow past one LLM call anyway and the
    body is read in Paperless, not the mirror.

    Args:
        page_count: Number of pages in the PDF.
        reformat_max_pages: Per-household cap from the archivist's bot
            settings.

    Returns:
        True when reformat is worth running.

    Examples:
        >>> should_reformat_pdf(1)
        True
        >>> should_reformat_pdf(5)
        True
        >>> should_reformat_pdf(6)
        False
        >>> should_reformat_pdf(30)
        False
        >>> should_reformat_pdf(15, reformat_max_pages=20)
        True
    """
    return page_count <= reformat_max_pages
