"""Write Sources/StackMenu/LogoOutline.swift: the outline of the famstack "a".

The mark is an "a" set in Inter Bold with two dots below it, laid out as in
famstack.dev's favicon.svg on a 32-unit grid: font size 28, centred at x 16,
baseline at y 22 (y grows downwards, as in the SVG). The app draws the
outline instead of shipping the font. Inter is under the SIL Open Font
License 1.1.

    uvx --with brotli --from fonttools python apps/macos/script/logo-outline.py \
        ../website/node_modules/@fontsource-variable/inter/files/inter-latin-wght-normal.woff2
"""

import sys
from pathlib import Path

from fontTools.pens.basePen import BasePen
from fontTools.ttLib import TTFont
from fontTools.varLib.instancer import instantiateVariableFont

FONT_SIZE, CENTER_X, BASELINE = 28, 16, 22
OUT = Path(__file__).resolve().parent.parent / "Sources/StackMenu/LogoOutline.swift"


class SwiftPen(BasePen):
    """Emits CGMutablePath calls in favicon grid coordinates."""

    def __init__(self, glyphset, scale, x0):
        super().__init__(glyphset)
        self.scale, self.x0, self.lines = scale, x0, []

    def pt(self, p):
        x = self.x0 + p[0] * self.scale
        y = BASELINE - p[1] * self.scale
        return f"CGPoint(x: {x:.3f}, y: {y:.3f})"

    def _moveTo(self, p):
        self.lines.append(f"        path.move(to: {self.pt(p)})")

    def _lineTo(self, p):
        self.lines.append(f"        path.addLine(to: {self.pt(p)})")

    def _qCurveToOne(self, c, p):
        self.lines.append(f"        path.addQuadCurve(to: {self.pt(p)}, control: {self.pt(c)})")

    def _curveToOne(self, c1, c2, p):
        self.lines.append(f"        path.addCurve(to: {self.pt(p)}, control1: {self.pt(c1)}, control2: {self.pt(c2)})")

    def _closePath(self):
        self.lines.append("        path.closeSubpath()")


font = instantiateVariableFont(TTFont(sys.argv[1]), {"wght": 700})
glyphs = font.getGlyphSet()
name = font.getBestCmap()[ord("a")]
scale = FONT_SIZE / font["head"].unitsPerEm
x0 = CENTER_X - glyphs[name].width * scale / 2
pen = SwiftPen(glyphs, scale, x0)
glyphs[name].draw(pen)

OUT.write_text(f"""import CoreGraphics

// Generated by script/logo-outline.py from Inter Bold (SIL Open Font License
// 1.1). The "a" of the famstack mark on favicon.svg's 32-unit grid, y down.

enum LogoOutline {{
    static let letterA: CGPath = {{
        let path = CGMutablePath()
{chr(10).join(pen.lines)}
        return path
    }}()
}}
""")
print(f"{OUT}: {len(pen.lines)} path elements")
