"""Post-setup hook for the photos stacklet.

Runs once after Immich is healthy. Creates the tech admin account via the
one-time admin-sign-up endpoint, then creates accounts for family
members listed in users.toml via setup.py.

Passwords come from secrets.toml (auto-generated by the harness).
"""

import json


def run(ctx):
    secret = ctx.secret
    step = ctx.step
    http_post = ctx.http_post

    from stack.users import TECH_ADMIN_USERNAME, TECH_ADMIN_EMAIL

    admin_password = secret("ADMIN_PASSWORD")
    if not admin_password:
        step("No admin password in secrets — skipping account creation")
        return

    # ── Create tech admin via one-time sign-up ───────────────────────
    step("Creating tech admin account...")
    try:
        http_post(
            "http://localhost:42010/api/auth/admin-sign-up",
            json.dumps({
                "email": TECH_ADMIN_EMAIL,
                "password": admin_password,
                "name": TECH_ADMIN_USERNAME,
            }),
            content_type="application/json",
        )
        step(f"Tech admin created ({TECH_ADMIN_EMAIL})")
    except Exception as e:
        err = str(e)
        if "400" in err:
            step("Tech admin already exists")
        else:
            step(f"Could not create tech admin: {e}")
            return

    # ── Log in to get a token ────────────────────────────────────────
    try:
        login = http_post(
            "http://localhost:42010/api/auth/login",
            json.dumps({
                "email": TECH_ADMIN_EMAIL,
                "password": admin_password,
            }),
            content_type="application/json",
        )
        token = login.get("accessToken")
        if not token:
            step("Login succeeded but no token returned")
            return
    except Exception as e:
        step(f"Could not log in as tech admin: {e}")
        return

    # Save the admin token for future API access
    secret("ADMIN_TOKEN", token)

    # ── Family member accounts ───────────────────────────────────────
    # Delegate to setup.py which handles all of this idempotently.
    ctx.stack.run_cli_command("photos", "setup")
